## Homework 02-1: due 2022/03/31 23:59 (30%)

#### - In this part, you should calculate the forward pass and backpropagation manually and there is no need for any coding.

#### - Please scan your hand-writting calculation and save it as HW2-1.pdf

#### - By running the following script, you can check your answer and observe how to do the backpropagation in PyTorch.

#### - You can change the iterations in script to observe how will the loss change.

##### 1. Please do the forward pass and backpropagation with a neural network as below, the input is 2 and the target is 1. Also, calculate the quadratic loss, 
##### i.e, $$Loss = \frac{1}{2}(y-y^*)^2$$ 
##### Please update the parameters twice, i.e., do two back propagation operations, and use the learning rate 0.01.

![train_ex.png](https://github.com/tingyan08/Deep-Learning-and-Computer-Vision/blob/main/HW2/img/HW2-1.png?raw=true)

In [2]:
import torch
import torch.nn as nn
import torch.optim as optim
from collections import OrderedDict

In [3]:
X = torch.tensor([2], dtype= torch.float32)
y = torch.tensor([1], dtype= torch.float32)

In [4]:
# Half of the sum square error
def loss(y, pred):
    return ((pred-y)**2).sum()/2

In [5]:
# Show parameters
def show_parameters(i, X, model):
    print(f"Iters {i}")
    print("Input:")
    print(X)
    for layer_name, layers in model.named_modules():
        print("-----------------------")
        if not isinstance(layers, nn.Sequential):
            for param_name, param in layers.named_parameters():
                print(f"{layer_name} {param_name} {param}")
                print(f"{layer_name} {param_name} Gradient")
                print(param.grad)
            print(f"{layer_name} output:")
            X = layers(X)
            print(X)
            
    print("===============================================")

In [6]:
def initialize_weights(model):
    for name, i in model.named_modules():
        if isinstance(i, nn.Linear):
            nn.init.constant_(i.weight.data, 1)
            nn.init.constant_(i.bias.data, -0.5)

In [9]:
print(model)

Sequential(
  (Layer1): Linear(in_features=1, out_features=2, bias=True)
  (ReLU1): ReLU()
  (Layer2): Linear(in_features=2, out_features=2, bias=True)
  (ReLU2): ReLU()
  (Layer3): Linear(in_features=2, out_features=1, bias=True)
)


In [8]:
model = nn.Sequential(OrderedDict([("Layer1", nn.Linear(1, 2)), 
                                   ("ReLU1", nn.ReLU()),
                                   ("Layer2", nn.Linear(2, 2)), 
                                   ("ReLU2", nn.ReLU()),
                                   ("Layer3", nn.Linear(2, 1))]))
initialize_weights(model)
lr = 0.1
n_iters = 100
optimizer = optim.SGD(model.parameters(), lr=lr, momentum=0)
loss_list = []
for i in range(n_iters+1):
    optimizer.zero_grad()
    pred = model(X)
    l = loss(pred, y)
    loss_list.append(l.detach().numpy())
    l.backward()
    show_parameters(i, X, model)
    optimizer.step()

Iters 0
Input:
tensor([2.])
-----------------------
-----------------------
Layer1 weight Parameter containing:
tensor([[1.],
        [1.]], requires_grad=True)
Layer1 weight Gradient
tensor([[14.],
        [14.]])
Layer1 bias Parameter containing:
tensor([-0.5000, -0.5000], requires_grad=True)
Layer1 bias Gradient
tensor([7., 7.])
Layer1 output:
tensor([1.5000, 1.5000], grad_fn=<AddBackward0>)
-----------------------
ReLU1 output:
tensor([1.5000, 1.5000], grad_fn=<ReluBackward0>)
-----------------------
Layer2 weight Parameter containing:
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
Layer2 weight Gradient
tensor([[5.2500, 5.2500],
        [5.2500, 5.2500]])
Layer2 bias Parameter containing:
tensor([-0.5000, -0.5000], requires_grad=True)
Layer2 bias Gradient
tensor([3.5000, 3.5000])
Layer2 output:
tensor([2.5000, 2.5000], grad_fn=<AddBackward0>)
-----------------------
ReLU2 output:
tensor([2.5000, 2.5000], grad_fn=<ReluBackward0>)
-----------------------
Layer3 weight Para